--- 
exclude: 
  - /SpeectInstaller/.*
  - /DeSpeect/Test/.*
  - /DeSpeect/Qt/.*
languages: 
  - name: cpp
    production: 
      include: 
        - /DeSpeect/Model/.*
    test: 
      include: 
        - /DeSpeect/Test/.*
