--- 
addons: 
  apt: 
    packages: 
      - cmake
      - gcc-7
      - g++-7
      - swig
      - libxml2-dev
      - python-dev
      - python-sphinx
      - doxygen
    sources: 
      - ubuntu-toolchain-r-test
after_success: 
  - "coveralls --root . -E \".*gtest.*\" -E \".*CMakeFiles.*\""
before_install: 
  - "eval \"${MATRIX_EVAL}\""
  - "pip install --user cpp-coveralls"
  - "sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa"
  - "sudo apt-get update -qq"
  - "sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev"
  - "sudo apt-get install qt5-default qttools5-dev-tools"
compiler: 
  - gcc
env: 
  - "MATRIX_EVAL=\"CC=gcc-7 && CXX=g++-7\""
install: 
  - "sudo apt-get update"
  - "sudo apt-get install libcppunit-dev"
language: cpp
notifications: 
  email: false
script: 
  - "gcc --version"
  - ./build.sh
sudo: required
